### ISSUE TITLE
Some confusion in your paper

### ISSUE THREAD

**Issue by zq1335030905** [cap-ntu/FedReID#14]
Thanks for your great job, I am work on federated leraning now. In your paper, in Table 2, the performance comparison of federated-by-camera scenario, federated-by-identity-scenario and local training. My confusion is:
Why the performance in federated-by-identity is better than that in local training on the CUHK03-NP but worse in Market-1501. I cannot found some anlysis in your paper.

**Comment by weimingwill** [comment]
@zq1335030905 Hi, it could be due to the number of clients. On the Market dataset, we consider 6 clients (as there are 6 cameras), which is harder than the scenario of the CUHK03 dataset where we consider 2 clients (as there are only 2 cameras).
