### ISSUE TITLE
Apply for the processed datasets.

### ISSUE THREAD

**Issue by Sunshine19980919** [cap-ntu/FedReID#18]
Hello.

Thank you for your wonderful paper and code work, and deeply express my admiration.

Recently, I am very interested in your work. However, I do not have the data set processed in the paper. Can you provide the application process of applying for preprocessed datasets? (the original application link has expired)

I use these datasets to run some comparative experiments and reproduce the work of this paper.

**Comment by weimingwill** [comment]
@Sunshine19980919 Please send an email to wingalong@gmail.com with a short self-introduction to apply for the dataset. Thank you.

**Comment by Sunshine19980919** [comment]
Thank you for your reply. The email has been delivered
