### ISSUE TITLE
About split.json

### ISSUE THREAD

**Issue by Jingruomu** [cap-ntu/FedReID#2]
I cannot find the split.json in small dataset, if i need to write a new one and how to do it?
Thanks

**Comment by Jingruomu** [comment]
i found the answer in issues#1

**Comment by weimingwill** [comment]
@Jingruomu You can email me with a short introduction if you need it now.

**Comment by Jingruomu** [comment]
> @Jingruomu You can email me with a short introduction if you need it now.

Thanks, i already sent an email to you.

**Comment by Grassyue** [comment]
> > @Jingruomu You can email me with a short introduction if you need it now.
> 
> Thanks, i already sent an email to you.
hi, sorry to bother you.
have you receive the file of split.json from the author？I have send an email to the author a few days, but did not reply me.

**Comment by Grassyue** [comment]
> > @Jingruomu You can email me with a short introduction if you need it now.
> 
> Thanks, i already sent an email to you.

hi, sorry to bother you.
have you receive the file of split.json from the author？I have send an email to the author a few days, but did not reply me.

**Comment by Jingruomu** [comment]
> have you receive the file of split.json from the author？I have send an email to the author a few days, but did not reply me.

yes，author sent it to me but i cannot publish it
