### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/3dpes/split.json'

### ISSUE THREAD

**Issue by pika1110** [cap-ntu/FedReID#3]
while running the command "python prepare_all_datasets.py" ,we met a bug that FileNotFoundError: [Errno 2] No such file or directory: 'data/3dpes/split.json'.Could you tell me how to solve the problem?

**Comment by weimingwill** [comment]
@pika1110  We haven't officially released these files. Please send me an email with a short intro if you need it now.

**Comment by pika1110** [comment]
Thank you for your reply, I've already sent an email to you.

**Comment by Grassyue** [comment]
> Thank you for your reply, I've already sent an email to you.

hi, sorry to bother you.
have you receive the file of split.json from the author？I have send an email to the author a few days, but did not reply me.
