### ISSUE TITLE
 FileNotFoundError

### ISSUE THREAD

**Issue by tsa18** [cap-ntu/FedReID#4]
While running the command "python prepare_all_datasets.py" ,I met a bug that FileNotFoundError: [Errno 2] No such file or directory: 'data/cuhk02\\meta.json''. And I can't find the file in the repository, could you please help me？ Thanks very much!

**Comment by weimingwill** [comment]
Hi @tsa18, the meta.json file comes with the dataset you downloaded. Due to regulation constraints, we are sorry that we are unable to provide the datasets in this repo. I believe that you can find other sources to download the dataset.
