### ISSUE TITLE
Question About the function `cdw_feature_distance`? 

### ISSUE THREAD

**Issue by wnma3mz** [cap-ntu/FedReID#6]
Hi!

The work on this article is really great! I hope to learn something from **FedReID**. 

But when read the code, the function `cdw_feature_distance` is confusing. Although I know Python can do it, why calculate the mean of `distance` in for loop.

https://github.com/cap-ntu/FedReID/blob/b63d990713eede5cbe254056713c755c664e1caa/optimization.py#L9-L25

Here's what I think

```python
         distance_lst = []
         for data in self.train_loader: 
             # do something
             distance = 1 - torch.cosine_similarity(old_out, new_out) 
             distance_lst.append(torch.mean(distance))
         return torch.mean(distance_lst)
```

Your reply will be greatly appreciated.

**Comment by codergan** [comment]
Hi, Thank you for your interests in this! We return in the for loop is because we only randomly sample one batch data for the distance measuring instead of whole training dataset

**Comment by wnma3mz** [comment]
> Hi, Thank you for your interests in this! We return in the for loop is because we only randomly sample one batch data for the distance measuring instead of whole training dataset

Yes, i see it in this paper. But why do it?

**Comment by codergan** [comment]
Yah, speed is definitely the concern, and using one batch is good enough for measuring the cosine distance.

**Comment by wnma3mz** [comment]
Thanks to answer!
