### ISSUE TITLE
aggregation models weird weights.

### ISSUE THREAD

**Issue by sycophant-stone** [cap-ntu/FedReID#9]
https://github.com/cap-ntu/FedReID/blob/master/server.py#L45-L49

see I have `N` models.
the `N`-th model will not get fair weight, because the `total_no_data` is (model-0, model-N-1), which dominates. 
pretty weird.

**Comment by weimingwill** [comment]
You can try to work through it with an example: models (m1, m2, m3), weights (w1, w2, w3). The computation is correct.

Note: weights here mean data sizes.

The computation will give you `(m1*w1 + m2*w2 + m3*w3) / (w1 + w2 + w3)`
